AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Deployment practice using jenkins jobs and jenkins pipeline'
Resources:
  JenkinsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  JenkinsPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.1.0/24
      VpcId:
        Ref: JenkinsVPC
  JenkinsIGW:
    Type: AWS::EC2::InternetGateway

  JenkinsRoute:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref JenkinsIGW
      RouteTableId: !Ref JenkinsRouteTable
    DependsOn: 
      - JenkinsIGW 
      - JenkinsRouteAttachment

  JenkinsRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref JenkinsVPC

  JenkinsRouteAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:  !Ref JenkinsIGW       
      VpcId: !Ref JenkinsVPC

  JenkinsAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup    
    Properties:
        AutoScalingGroupName: JenkinsASG
        MaxSize: 1
        MinSize: 1
        AvailabilityZones: 
          - us-east-1a
          - us-east-1b
        LaunchTemplate:     
          LaunchTemplateId: !Ref JenkinsLaunchTemplate   
          Version: !GetAtt JenkinsLaunchTemplate.LatestVersionNumber
     

  JenkinsLaunchTemplate:          
    Type: AWS::EC2::LaunchTemplate
    Properties:       
      LaunchTemplateData: 
        ImageId:  ami-0747bdcabd34c712a
        InstanceType: t2.micro

  JenkinsEC2: 
    Type: AWS::EC2::Instance
    Properties: 
        UserData:
        Fn::Base64: |
            #!/bin/bash -xe
            wget 
      
        KeyName: homebase
        SecurityGroupIds:
            - sg-0801e39ba60d03c7a

        LaunchTemplate: 
          LaunchTemplateId: !Ref JenkinsLaunchTemplate
          Version: !GetAtt JenkinsLaunchTemplate.LatestVersionNumber

   
